import type { ApiEnvelope, CurrentUser, DashboardSummary, Employee, ListResponse, MeResponse, ModuleRecord, RequestOptions, Session } from '@/lib/types'
export * from '@/lib/types'
const API_BASE_URL = (process.env.NEXT_PUBLIC_API_BASE_URL || 'http://localhost:8080/api/v1').replace(/\/$/, '')
const SESSION_KEY = 'emplyra.session'
let accessToken: string | null = null
let refreshToken: string | null = null
let tenantId: string | null = null
let refreshFlight: Promise<Session> | null = null
function persist(session: Session | null) { accessToken = session?.access_token ?? null; refreshToken = session?.refresh_token ?? null; if (typeof window !== 'undefined') { if (session) window.sessionStorage.setItem(SESSION_KEY, JSON.stringify(session)); else window.sessionStorage.removeItem(SESSION_KEY) } }
export function setSession(session: Session | null) { persist(session); if (!session) setTenantId(null) }
export function restoreSession() { if (typeof window === 'undefined') return null; try { const value = JSON.parse(window.sessionStorage.getItem(SESSION_KEY) || 'null') as Session | null; if (value?.access_token) { persist(value); return value } } catch {} window.sessionStorage.removeItem(SESSION_KEY); return null }
export const hasSession = () => Boolean(accessToken)
export const setTenantId = (id: string | null) => { tenantId = id }
export const getTenantId = () => tenantId
async function refresh() { if (!refreshToken) throw new Error('Your session has expired. Please sign in again.'); if (!refreshFlight) refreshFlight = request<Session>('/auth/refresh', { method: 'POST', body: JSON.stringify({ refresh_token: refreshToken }) }, false).finally(() => { refreshFlight = null }); const session = await refreshFlight; persist(session); return session }
async function request<T>(path: string, init: RequestInit = {}, canRefresh = true): Promise<T> { const headers = new Headers(init.headers); if (!(init.body instanceof FormData)) headers.set('Content-Type', 'application/json'); if (accessToken) headers.set('Authorization', `Bearer ${accessToken}`); if (tenantId) headers.set('X-Tenant-ID', tenantId); const response = await fetch(`${API_BASE_URL}${path}`, { ...init, headers, cache: 'no-store' }); const payload = await response.json().catch(() => null) as ApiEnvelope<T> | null; if (response.status === 401 && canRefresh && refreshToken) { await refresh(); return request(path, init, false) } if (!response.ok || payload?.success === false) { const errors = payload?.errors; const message = payload?.message || (Array.isArray(errors) ? errors.join(', ') : errors && Object.values(errors).join(', ')); throw new Error(message || `Request failed with status ${response.status}`) } if (!payload || !('data' in payload)) throw new Error(`Request failed with status ${response.status}`); return payload.data }
function withQuery(path: string, options: RequestOptions = {}) { const params = new URLSearchParams({ page: String(options.page ?? 1), page_size: String(options.pageSize ?? 20) }); if (options.search?.trim()) params.set('search', options.search.trim()); Object.entries(options.query ?? {}).forEach(([key, value]) => { if (value !== undefined) params.set(key, String(value)) }); return `${path}?${params}` }
const list = <T,>(path: string, options?: RequestOptions) => request<ListResponse<T>>(withQuery(path, options))
const crud = <T>(path: string) => ({ list: (o?: RequestOptions) => list<T>(path, o), get: (id: string) => request<T>(`${path}/${encodeURIComponent(id)}`), create: (body: unknown) => request<T>(path, { method: 'POST', body: JSON.stringify(body) }), update: (id: string, body: unknown) => request<T>(`${path}/${encodeURIComponent(id)}`, { method: 'PUT', body: JSON.stringify(body) }), remove: (id: string) => request<unknown>(`${path}/${encodeURIComponent(id)}`, { method: 'DELETE' }) })
export const api = { login: (identifier: string, password: string) => request<{ tokens: Session; user: CurrentUser }>('/auth/login', { method: 'POST', body: JSON.stringify({ identifier, password }) }, false), me: () => request<MeResponse>('/auth/me'), logout: () => request<unknown>('/auth/logout', { method: 'POST', body: JSON.stringify({ refresh_token: refreshToken }) }, false), dashboard: () => request<DashboardSummary>('/dashboard/summary'), employees: (page=1, pageSize=10, search='') => list<Employee>('/employees', { page, pageSize, search }), employee: crud<Employee>('/employees'), module: (path: string, options?: RequestOptions) => list<ModuleRecord>(path, options), attendanceCheckIn: () => request<ModuleRecord>('/attendance/check-in', { method: 'POST', body: JSON.stringify({}) }), attendanceCheckOut: () => request<ModuleRecord>('/attendance/check-out', { method: 'POST', body: JSON.stringify({}) }), leaveTypes: () => list<ModuleRecord>('/leaves/types', { pageSize: 50 }), createLeave: (body: Record<string, unknown>) => request<ModuleRecord>('/leaves', { method: 'POST', body: JSON.stringify(body) }), notifications: () => list<ModuleRecord>('/notifications', { pageSize: 20 }), unreadCount: () => request<{ count: number }>('/notifications/unread-count'), markAllRead: () => request<unknown>('/notifications/read-all', { method: 'PUT' }) }
export const getApiBaseUrl = () => API_BASE_URL
